//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project02.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project02.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Drawing;
        ///using System.Drawing.Drawing2D;
        ///using System.Drawing.Text;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///
        ///public class LollipopButton : Control
        ///{
        ///
        ///    #region  Variables
        ///
        ///    Timer AnimationTimer = new Timer { Interval = 1 };
        ///
        ///    FontManager font = new FontManager();
        ///    StringFormat SF = new StringFormat();
        ///    Rectangle R;
        ///
        ///    bool Foc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LollipopButton {
            get {
                return ResourceManager.GetString("LollipopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.ComponentModel.Design;
        ///using System.Drawing;
        ///using System.Drawing.Design;
        ///using System.Drawing.Drawing2D;
        ///using System.Drawing.Text;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///
        ///public class LollipopCard : Control
        ///{
        ///
        ///    #region Variables
        ///
        ///    Image image;
        ///    Label InfoLabel = new Label();
        ///    FontManager font = new FontManager();
        ///    LollipopFla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LollipopCard {
            get {
                return ResourceManager.GetString("LollipopCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Drawing;
        ///using System.Drawing.Drawing2D;
        ///using System.Drawing.Text;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///
        ///public class LollipopCheckBox : CheckBox
        ///{
        ///    #region Variables
        ///
        ///    static Point[] CHECKMARK_LINE = { new Point(3, 8), new Point(7, 12), new Point(14, 5) };
        ///
        ///    string HexColor = &quot;#508ef5&quot;;
        ///
        ///    Color EnabledCheckedColor;
        ///    Color En [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LollipopCheckBox {
            get {
                return ResourceManager.GetString("LollipopCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Drawing;
        ///using System.Drawing.Drawing2D;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///
        ///[DefaultEvent(&quot;TextChanged&quot;)]
        ///public class LollipopFileInput : Control
        ///{
        ///
        ///    #region  Variables
        ///
        ///    Button InPutBTN = new Button();
        ///    TextBox LollipopTB = new TextBox();
        ///
        ///    HorizontalAlignment ALNType;
        ///    int maxchars = 32767;
        ///    bool readOnly;
        ///    boo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LollipopFileInput {
            get {
                return ResourceManager.GetString("LollipopFileInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Drawing;
        ///using System.Drawing.Drawing2D;
        ///using System.Drawing.Text;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///
        ///public class LollipopFlatButton : Control
        ///{
        ///
        ///    #region  Variables
        ///
        ///    Timer AnimationTimer = new Timer { Interval = 1 };
        ///
        ///    FontManager font = new FontManager();
        ///    StringFormat SF = new StringFormat();
        ///    Rectangle R;
        ///
        ///    bool [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LollipopFlatButton {
            get {
                return ResourceManager.GetString("LollipopFlatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Drawing;
        ///using System.Drawing.Drawing2D;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///
        ///[DefaultEvent(&quot;TextChanged&quot;)]
        ///public class LollipopFolderInPut : Control
        ///{
        ///
        ///    #region  Variables
        ///
        ///    Button InPutBTN = new Button();
        ///    TextBox LollipopTB = new TextBox();
        ///
        ///    HorizontalAlignment ALNType;
        ///    int maxchars = 32767;
        ///    bool readOnly;
        ///    boo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LollipopFolderInPut {
            get {
                return ResourceManager.GetString("LollipopFolderInPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Drawing;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///
        ///
        ///public class LollipopLabel : Label
        ///{
        ///    FontManager font = new FontManager();
        ///    public LollipopLabel()
        ///    {
        ///        this.Font = font.Roboto_Medium10;
        ///        ForeColor = ColorTranslator.FromHtml(&quot;#999999&quot;);
        ///        BackColor = Color.Transparent;
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string LollipopLabel {
            get {
                return ResourceManager.GetString("LollipopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Drawing;
        ///using System.Drawing.Drawing2D;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///
        ///
        ///
        ///public class LollipopProgressBar : Control
        ///{
        ///    #region variables
        ///    
        ///    int ProgressNum = 10;
        ///    string ProgressColor = &quot;#508ef5&quot;;
        ///
        ///    Color BackGroundColor;
        ///
        ///    #endregion
        ///    #region Properties
        ///
        ///    [Category(&quot;Appearance&quot;)]
        ///    public string BGColo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LollipopProgressBar {
            get {
                return ResourceManager.GetString("LollipopProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Drawing;
        ///using System.Drawing.Drawing2D;
        ///using System.Drawing.Text;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///
        ///public class LollipopRadioButton : RadioButton
        ///{
        ///    #region Variables
        ///
        ///    string HexColor = &quot;#508ef5&quot;;
        ///
        ///    Color EnabledCheckedColor;
        ///    Color EnabledUnCheckedColor = ColorTranslator.FromHtml(&quot;#9c9ea1&quot;);
        ///
        ///    Color DisabledColor = Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LollipopRadioButton {
            get {
                return ResourceManager.GetString("LollipopRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Drawing;
        ///using System.Drawing.Drawing2D;
        ///using System.Drawing.Text;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///
        ///public class LollipopSmallCard : Control
        ///{
        ///
        ///    #region Variables
        ///  
        ///    FontManager font = new FontManager();
        ///    Image image;
        ///
        ///    string information = &quot;Info&quot;;
        ///    string fontcolor = &quot;#33b679&quot;;
        ///    string thumbnailcolor = &quot;#33b679&quot;;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LollipopSmallCard {
            get {
                return ResourceManager.GetString("LollipopSmallCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Drawing;
        ///using System.Drawing.Drawing2D;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///
        ///[DefaultEvent(&quot;TextChanged&quot;)]
        ///public class LollipopTextBox : Control
        ///{
        ///
        ///    #region  Variables
        ///
        ///    TextBox LollipopTB = new TextBox();
        ///    HorizontalAlignment ALNType;
        ///
        ///    int maxchars = 32767;
        ///    bool readOnly;
        ///    bool previousReadOnly;
        ///    bool multiline;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LollipopTextBox {
            get {
                return ResourceManager.GetString("LollipopTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Drawing;
        ///using System.Drawing.Drawing2D;
        ///using System.Drawing.Text;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Windows.Forms;
        ///
        ///public class LollipopToggle : CheckBox
        ///{
        ///    #region Variables
        ///
        ///    Timer AnimationTimer = new Timer { Interval = 1 };
        ///    GraphicsPath RoundedRectangle;
        ///
        ///    string EllipseBG = &quot;#508ef5&quot;;
        ///    string EllipseBorder = &quot;#3b73d1&quot;;
        ///
        ///    Colo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LollipopToggle {
            get {
                return ResourceManager.GetString("LollipopToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Roboto_Medium {
            get {
                object obj = ResourceManager.GetObject("Roboto_Medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Roboto_Regular {
            get {
                object obj = ResourceManager.GetObject("Roboto_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
